### ISSUE TITLE
[backend]Geração de certificados assinados

### ISSUE THREAD

**Issue by willianSanches13** [willianSanches13/presence-hub#11]

**Comment by DeAvreux** [comment]
Tela de Visualização de Registros e Emissão de Relatórios/Certificados - Backend
1. Rota para Visualizar Registros de Frequência
Descrição: Criar um endpoint para retornar os registros de frequência com base nos filtros selecionados.
Tarefas:

Definir o endpoint GET /api/frequencias.
Implementar filtros opcionais para:
aula_id (para exibir registros de uma aula específica).
turma_id (para exibir registros de todos os alunos de uma turma).
aluno_id (para exibir registros individuais de um aluno).
Retornar informações como:
Nome do aluno, matrícula.
Status da frequência (presente/faltante) para cada aula.
Percentuais de presença e falta.
2. Rota para Emissão de Relatórios
Descrição: Criar um endpoint para gerar relatórios de frequência no formato PDF.
Tarefas:

Definir o endpoint POST /api/relatorios/frequencia.
Permitir filtros:
Individual (aluno_id).
Agrupado por turma (turma_id).
Agrupado por aula (aula_id).
Gerar o relatório com:
Nome da turma, aula, data.
Alunos, matrículas, status de presença e percentuais de frequência.
Data de geração e informações do professor.
3. Rota para Emissão de Certificados
Descrição: Criar um endpoint para emitir certificados de participação com carga horária.
Tarefas:

Definir o endpoint POST /api/certificados.
Receber aluno_id e turma_id ou aula_id como parâmetros.
Validar se o aluno cumpre o percentual mínimo de presença para receber o certificado (ex: 75%).
Gerar o certificado no formato PDF com os seguintes dados:
Nome do aluno.
Nome da turma ou aula e carga horária.
Data de emissão e assinatura do professor.
4. Testes Unitários e de Integração
Descrição: Garantir a integridade e funcionalidade das rotas criadas.
Tarefas:

Testar os filtros no endpoint de registros.
Verificar a geração correta de relatórios com diferentes filtros.
Validar a emissão de certificados apenas para alunos elegíveis.
