### ISSUE TITLE
[frontend]Geração de certificados assinados

### ISSUE THREAD

**Issue by willianSanches13** [willianSanches13/presence-hub#12]

**Comment by DeAvreux** [comment]
Tela de Visualização e Emissão - Frontend (React)
1. Exibição de Registros de Frequência
Descrição: Criar uma interface que permita ao professor visualizar os registros de frequência.
Tarefas:

Criar filtros para selecionar:
Uma aula específica (dropdown de aulas).
Uma turma específica (dropdown de turmas).
Um aluno específico (campo de busca ou dropdown).
Renderizar uma tabela com:
Nome do aluno, matrícula.
Status de presença por aula (ícones ou textos).
Percentuais de presença e falta.
Adicionar paginação para turmas grandes.
2. Emissão de Relatórios
Descrição: Implementar a funcionalidade para gerar relatórios de frequência em PDF.
Tarefas:

Criar botões para "Relatório Individual", "Relatório por Turma" e "Relatório por Aula".
Enviar os dados filtrados para o endpoint /api/relatorios/frequencia.
Baixar o arquivo PDF gerado.
3. Emissão de Certificados de Participação
Descrição: Permitir a emissão de certificados de participação individuais.
Tarefas:

Adicionar um botão "Emitir Certificado" próximo a cada aluno na tabela.
Validar a elegibilidade do aluno (percentual de presença >= 75%).
Enviar a solicitação para o endpoint /api/certificados.
Baixar o arquivo PDF gerado.
4. Gerenciamento de Estado
Descrição: Usar hooks para gerenciar os estados da interface.
Tarefas:

Criar estados para armazenar filtros (aulaSelecionada, turmaSelecionada, alunoSelecionado).
Armazenar os registros de frequência e os percentuais de presença/falta.
Atualizar a tabela e as opções do menu com base nos filtros aplicados.
5. Feedback Visual
Descrição: Fornecer uma interface intuitiva e responsiva para o professor.
Tarefas:

Exibir ícones para status de presença (ex: ✅ para "Presente", ❌ para "Faltante").
Mostrar mensagens de erro caso nenhum registro seja encontrado para os filtros selecionados.
Exibir spinners durante o carregamento de dados ou geração de PDFs.
6. Testes Unitários e de Integração
Descrição: Validar a funcionalidade da interface de visualização e emissão.
Tarefas:

Testar a exibição dos registros de frequência para diferentes filtros.
Verificar a geração correta de relatórios e certificados.
Testar os cenários de erro, como ausência de registros ou ineligibilidade para certificados.
7. Acessibilidade e Responsividade
Descrição: Garantir que a interface seja acessível e adaptada a diferentes dispositivos.
Tarefas:

Certificar que os botões e tabelas sejam navegáveis via teclado.
Garantir que o layout se ajuste bem em telas menores.
Adicionar rótulos descritivos para elementos interativos (atributo aria-label).

**Comment by DeAvreux** [comment]
Tela de Consulta de Frequência e Emissão de Certificados - Frontend (React)
1. Exibição das Turmas e Frequências do Aluno
Descrição: Permitir que o aluno veja a lista de turmas em que está matriculado e suas frequências.
Tarefas:

Criar uma interface que exiba:
Nome da turma e carga horária.
Percentual de presença.
Lista de aulas com datas e status de presença (ícones para "Presente" e "Faltante").
Implementar uma chamada ao endpoint /api/alunos/{aluno_id}/frequencias para buscar os dados.
Adicionar feedback visual caso o aluno não tenha frequências registradas ou não esteja matriculado em turmas.
2. Emissão e Download de Certificados
Descrição: Permitir que o aluno emita certificados de turmas concluídas.
Tarefas:

Adicionar um botão "Emitir Certificado" ao lado de cada turma com percentual de presença >= 75%.
Ao clicar no botão:
Enviar os dados para o endpoint /api/certificados/emitir.
Baixar o PDF gerado automaticamente ou exibir um link para download.
Mostrar uma mensagem de erro se o aluno não atingir o percentual mínimo.
3. Gerenciamento de Estado
Descrição: Usar hooks para gerenciar os estados da interface.
Tarefas:

Criar estados para armazenar:
Lista de turmas com frequências (turmas).
Status de carregamento e mensagens de erro (loading, error).
Atualizar a interface ao emitir certificados ou ao carregar as turmas.
4. Feedback Visual para o Aluno
Descrição: Tornar a interface intuitiva e responsiva.
Tarefas:

Exibir ícones para status de presença nas aulas (✅ para "Presente", ❌ para "Faltante").
Mostrar mensagens claras, como:
"Você ainda não possui turmas registradas."
"Você atingiu o percentual necessário para emitir o certificado."
Adicionar animações de carregamento enquanto os dados são buscados ou o certificado é emitido.
5. Testes Unitários e de Integração
Descrição: Garantir a funcionalidade de consulta de frequências e emissão de certificados.
Tarefas:

Testar a renderização correta das turmas e suas frequências.
Validar a emissão e download de certificados em cenários elegíveis.
Testar o feedback visual e mensagens de erro.
6. Acessibilidade e Responsividade
Descrição: Garantir que a interface funcione bem em diferentes dispositivos e seja acessível.
Tarefas:

Certificar que a interface seja navegável via teclado.
Garantir que a página seja responsiva, adaptando-se a telas menores.
Adicionar rótulos descritivos para botões e links (atributo aria-label).
